### PR TITLE
Incorporate some of Gilson edits, add new figures, compress cites

### PR DESCRIPTION
**Pull request by davidlmobley**
- [x] Fix minor issue with wrapped figure
- [x] Compress/renumber SAMPL citations by adding a phantom citation 
- [x] Incorporate minor Gilson edits
- [x] Create issues for more involved Gilson edits
- [x] Incorporate typo fixes from Lyle
- [x] Fix "orphans" introduced by renumbering of references
- [ ] Add drafts of other figures

### CODE REVIEW

**Comment by davidlmobley** [comment]
Still working on figuring out what would be the best figures -- lots of data buried in old papers that is not particularly easy to work with. At this point I'm thinking it may be something like this relating to SAMPL history:
- Number of (and/or fraction of) "well performing" methods over time for hydration, determined by being basically within error of the best method (this has gone up over time as people learn from what worked, though it also occasionally goes down when someone has a new advance)
- host-guest scatter plot (calc vs expt) comparison of the best method in SAMPL3 vs best in SAMPL5; possibly also something similar on hydration
- number of participants and submissions by challenge component and aggregated, as a function of time

**Comment by jchodera** [comment]
I had trouble preparing such a figure too for my ACS talk. Here are some things I came up with. in case they inspire anything:

[sampl-slides.pdf](https://github.com/choderalab/SAMPL-R01/files/501953/sampl-slides.pdf)

**Comment by jchodera** [comment]
All of these are great ideas for plots, but the way.

**Comment by davidlmobley** [comment]
I'll go ahead and merge this in case you want to edit, as I'll be offline shortly. I'll send you some figure ideas on Slack for comments as soon as I finish drafting...

**Pull request merged**
